# Generated by Django 4.0.3 on 2022-04-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchllist',
            new_name='watchlist',
        ),
    ]
